ALLOWED_CRDS := "ComputeAddress,ComputeForwardingRule,ComputeServiceAttachment,RunService,CloudSchedulerJob,IAMPolicyMember"
OPERATOR_TAG := 0.1.1
IMAGE := eu.gcr.io/birota-cloud/cnrm-operator:${OPERATOR_TAG}

fix-crds:
	cd fix-manifests && go mod tidy
	cd fix-manifests && go run . ${ALLOWED_CRDS}

build-operator:
	docker build -t ${IMAGE} -f operator/Dockerfile .
	
push-operator: build-operator
	docker push ${IMAGE}
