label: Config Connector RunService
markdownDescription: Creates yaml for a RunService resource
insertText: |
  apiVersion: run.cnrm.cloud.google.com/v1beta1
  kind: RunService
  metadata:
    name: \${1:runservice-name}
  spec:
    ingress: \${2:INGRESS_TRAFFIC_ALL}
    launchStage: \${3:GA}
    location: \${4:us-central1}
    projectRef:
      external: \${5:projects/[PROJECT_ID?]}
    template:
      containers:
      - image: \${6:gcr.io/cloudrun/hello}
        volumeMounts:
        - name: \${7:a-volume}
          mountPath: \${8:/secrets}
      volumes:
      - name: \${9:a-volume}
        secret:
          secretRef:
            name: \${10:runservice-dep-secret}
            defaultMode: \${11:292}
            items:
            - versionRef:
                name: \${12:runservice-dep-secret}
                path: \${13:my-secret}
                mode: \${14:256}
