apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    cnrm.cloud.google.com/operator-version: 1.101.0
  labels:
    cnrm.cloud.google.com/operator-system: "true"
  name: configconnector-operator-cnrm-system-auth-delegator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  # NB: This service account is created at runtime
  - kind: ServiceAccount
    name: cnrm-controller-manager
    namespace: cnrm-system
